language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install -y libevent-dev
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
notifications:
  email:
    recipients:
      - douglas.patti@gmail.com
    on_success: change
    on_failure: always
